<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <PackageVersion>9.3.2</PackageVersion>
        <Authors>Robin Nunkesser</Authors>
        <PackageProjectUrl>https://github.com/Italbytz/nuget-ml-ucimlr</PackageProjectUrl>
        <Description>Provides Data Sets from the UC Irvine Machine Learning Repository for Microsoft.ML.</Description>
        <PackOnBuild>true</PackOnBuild>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>introduction.md</PackageReadmeFile>
        <RepositoryUrl>https://github.com/Italbytz/nuget-ml-ucimlr</RepositoryUrl>
        <LangVersion>12</LangVersion>
        <PackRelease>true</PackRelease>
        <IncludeSource>true</IncludeSource>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Italbytz.ML" Version="9.11.1"/>
        <PackageReference Include="Microsoft.ML" Version="4.0.2"/>
    </ItemGroup>

    <ItemGroup>
        <None Remove="Data\Heart_Disease.csv"/>
        <EmbeddedResource Include="Data\Heart_Disease.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Data\Iris.csv"/>
        <EmbeddedResource Include="Data\Iris.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Data\Wine_Quality.csv"/>
        <EmbeddedResource Include="Data\Wine_Quality.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Data\Breast_Cancer_Wisconsin_Diagnostic_.csv"/>
        <EmbeddedResource Include="Data\Breast_Cancer_Wisconsin_Diagnostic_.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Data\Heart_Disease_Binary.csv"/>
        <EmbeddedResource Include="Data\Heart_Disease_Binary.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Data\Adult.csv"/>
        <EmbeddedResource Include="Data\Adult.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Data\Student_Performance.csv"/>
        <EmbeddedResource Include="Data\Student_Performance.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Data\Student_Performance_G1.csv"/>
        <EmbeddedResource Include="Data\Student_Performance_G1.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Data\Student_Performance_G2.csv"/>
        <EmbeddedResource Include="Data\Student_Performance_G2.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Data\Student_Performance_G3.csv"/>
        <EmbeddedResource Include="Data\Student_Performance_G3.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Data\Automobile.csv"/>
        <EmbeddedResource Include="Data\Automobile.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Data\lenses.csv"/>
        <EmbeddedResource Include="Data\lenses.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Data\national_poll_on_healthy_aging_npha.csv"/>
        <EmbeddedResource Include="Data\national_poll_on_healthy_aging_npha.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Data\solarflare_1.csv"/>
        <EmbeddedResource Include="Data\solarflare_1.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Data\car_evaluation_strings.csv"/>
        <EmbeddedResource Include="Data\car_evaluation_strings.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Data\balancescale.csv"/>
        <EmbeddedResource Include="Data\balancescale.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Data\Estimation_of_Obesity_Levels_Based_On_Eating_Habits_and_Physical_Condition.csv"/>
        <EmbeddedResource Include="Data\Estimation_of_Obesity_Levels_Based_On_Eating_Habits_and_Physical_Condition.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
        <None Remove="Data\CDC_Diabetes_Health_Indicators.csv"/>
        <EmbeddedResource Include="Data\CDC_Diabetes_Health_Indicators.csv">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </EmbeddedResource>
    </ItemGroup>
    <ItemGroup>
        <None Include="../../docfx/docs/introduction.md" Pack="true" PackagePath="\"/>
    </ItemGroup>
</Project>
